apiVersion: network.sherpaholidays.com/v1alpha1
kind: Nginx
metadata:
  labels:
    app.kubernetes.io/name: nginx-opr
    app.kubernetes.io/managed-by: kustomize
  name: nginx-sample
spec:
  replicas: 1
  image: nginxinc/nginx-unprivileged:1.25
  port: 80
